version: '3.7'
services:
  java:
    env_file:
      - .env
    build:
      context: docker
      target: base
      args:
        JAVA_VERSION: $JAVA_VERSION
        MAVEN_VERSION: $MAVEN_VERSION
    image: bacluc/java:$JAVA_VERSION
    volumes:
      - ./hellofx:/home/app/hellofx
      - m2-cache:/home/app/.m2

  javavnc:
    env_file:
      - .env
    build:
      context: docker
      target: base
      args:
        JAVA_VERSION: $JAVA_VERSION
        MAVEN_VERSION: $MAVEN_VERSION
    image: bacluc/javavnc:$JAVA_VERSION
    volumes:
      - ./hellofx:/home/app/hellofx
      - m2-cache:/home/app/.m2
    ports:
      - 5900:5900
volumes:
  m2-cache: